export interface ListeningQuestion {
  id: string;
  audioText: string;
  question: string;
  options: string[];
  correct: number;
  type: 'comprehension' | 'dictation';
}

export interface ListeningLevelBlock {
  level: string;
  questions: ListeningQuestion[];
}

// Fisher-Yates shuffle + pick N
export function selectListeningQuestions(pool: ListeningQuestion[], count: number): ListeningQuestion[] {
  const shuffled = [...pool];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count);
}

export const LISTENING_QUESTIONS_PER_LEVEL = 5;
export const LISTENING_PASS_THRESHOLD = 3;

// ── English (CEFR A1–C1) ── 10 questions per level, 5 randomly selected
export const englishListeningPool: ListeningLevelBlock[] = [
  {
    level: 'A1',
    questions: [
      {
        id: 'en-A1-01',
        audioText: 'My name is Tom. I am from Canada.',
        question: 'Where is Tom from?',
        options: ['Japan', 'Canada', 'Australia', 'England'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-A1-02',
        audioText: 'The book is on the table.',
        question: 'What did you hear?',
        options: ['The book is on the table.', 'The book is under the table.', 'The bag is on the table.', 'The book is on the chair.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-A1-03',
        audioText: 'I have two cats and one dog.',
        question: 'How many cats does the speaker have?',
        options: ['One', 'Two', 'Three', 'Four'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-A1-04',
        audioText: 'She goes to school every morning.',
        question: 'What did you hear?',
        options: ['She goes to school every morning.', 'She goes to work every morning.', 'She goes to school every evening.', 'He goes to school every morning.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-A1-05',
        audioText: 'The weather is sunny today. It is very warm.',
        question: 'How is the weather?',
        options: ['Cold and rainy', 'Sunny and warm', 'Cloudy and cool', 'Snowy and cold'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-A1-06',
        audioText: 'I like apples and oranges.',
        question: 'What did you hear?',
        options: ['I like apples and oranges.', 'I like apples and bananas.', 'I eat apples and oranges.', 'I like grapes and oranges.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-A1-07',
        audioText: 'The store closes at nine o\'clock.',
        question: 'When does the store close?',
        options: ['At seven', 'At eight', 'At nine', 'At ten'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-A1-08',
        audioText: 'My favorite color is blue.',
        question: 'What did you hear?',
        options: ['My favorite color is blue.', 'My favorite color is green.', 'My favorite food is blue.', 'Her favorite color is blue.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-A1-09',
        audioText: 'There are five children in the park.',
        question: 'How many children are in the park?',
        options: ['Three', 'Four', 'Five', 'Six'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-A1-10',
        audioText: 'Please sit down and open your book.',
        question: 'What did you hear?',
        options: ['Please stand up and open your book.', 'Please sit down and close your book.', 'Please sit down and open your book.', 'Please sit down and open your bag.'],
        correct: 2,
        type: 'dictation',
      },
    ],
  },
  {
    level: 'A2',
    questions: [
      {
        id: 'en-A2-01',
        audioText: 'Excuse me, how do I get to the train station? Go straight for two blocks, then turn left.',
        question: 'Which direction should the person turn?',
        options: ['Right', 'Left', 'Straight', 'Back'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-A2-02',
        audioText: 'I usually wake up at seven, but yesterday I woke up at eight.',
        question: 'What did you hear?',
        options: ['I usually wake up at seven, but yesterday I woke up at eight.', 'I usually wake up at eight, but yesterday I woke up at seven.', 'I usually wake up at seven, but yesterday I woke up at nine.', 'I always wake up at seven, but yesterday I woke up at eight.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-A2-03',
        audioText: 'The supermarket is next to the bank. It opens at eight in the morning and closes at ten at night.',
        question: 'Where is the supermarket?',
        options: ['Next to the post office', 'Next to the bank', 'Next to the school', 'Next to the park'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-A2-04',
        audioText: 'She was cooking dinner when the phone rang.',
        question: 'What did you hear?',
        options: ['She was eating dinner when the phone rang.', 'She was cooking dinner when the phone rang.', 'She was cooking lunch when the phone rang.', 'She was cooking dinner when the bell rang.'],
        correct: 1,
        type: 'dictation',
      },
      {
        id: 'en-A2-05',
        audioText: 'I\'d like a cup of coffee, please. Would you like milk or sugar? Just milk, please.',
        question: 'What does the customer want in their coffee?',
        options: ['Sugar only', 'Milk only', 'Milk and sugar', 'Nothing'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-A2-06',
        audioText: 'We are going to visit London next week.',
        question: 'What did you hear?',
        options: ['We are going to visit London next week.', 'We are going to visit Paris next week.', 'We are going to visit London next month.', 'They are going to visit London next week.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-A2-07',
        audioText: 'The weather forecast says it will rain tomorrow, so don\'t forget your umbrella.',
        question: 'What should the listener bring?',
        options: ['A jacket', 'Sunglasses', 'An umbrella', 'A hat'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-A2-08',
        audioText: 'Last summer, my family and I traveled to Italy. We visited Rome and Florence.',
        question: 'Which cities did they visit?',
        options: ['Paris and London', 'Rome and Venice', 'Rome and Florence', 'Milan and Florence'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-A2-09',
        audioText: 'The movie starts at half past seven.',
        question: 'What did you hear?',
        options: ['The movie starts at half past seven.', 'The movie starts at half past six.', 'The movie ends at half past seven.', 'The show starts at half past seven.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-A2-10',
        audioText: 'My brother is taller than me, but I am faster than him.',
        question: 'Who is taller?',
        options: ['The speaker', 'The brother', 'They are the same', 'Not mentioned'],
        correct: 1,
        type: 'comprehension',
      },
    ],
  },
  {
    level: 'B1',
    questions: [
      {
        id: 'en-B1-01',
        audioText: 'I think social media has both advantages and disadvantages. On one hand, it helps people stay connected. On the other hand, it can be addictive.',
        question: 'What is the speaker\'s opinion about social media?',
        options: ['It is completely bad', 'It is completely good', 'It has both good and bad sides', 'They don\'t use it'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-B1-02',
        audioText: 'If I won the lottery, I would travel around the world.',
        question: 'What did you hear?',
        options: ['If I win the lottery, I will travel around the world.', 'If I won the lottery, I would travel around the world.', 'When I won the lottery, I traveled around the world.', 'If I won the lottery, I would buy a house.'],
        correct: 1,
        type: 'dictation',
      },
      {
        id: 'en-B1-03',
        audioText: 'The company announced that they would be hiring fifty new employees by the end of the year. Most positions will be in the marketing department.',
        question: 'Which department will have the most new positions?',
        options: ['Sales', 'Engineering', 'Marketing', 'Human Resources'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-B1-04',
        audioText: 'By the time we arrived at the station, the train had already left.',
        question: 'What did you hear?',
        options: ['By the time we arrived at the station, the train had already left.', 'By the time we arrived at the airport, the train had already left.', 'By the time we arrived at the station, the bus had already left.', 'When we arrived at the station, the train was leaving.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-B1-05',
        audioText: 'When I was a child, I used to spend every summer at my grandparents\' farm. Those were some of the happiest memories of my life.',
        question: 'How does the speaker feel about those memories?',
        options: ['Sad', 'Angry', 'Happy', 'Confused'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-B1-06',
        audioText: 'The woman who lives next door is a doctor at the local hospital.',
        question: 'What did you hear?',
        options: ['The woman who lives next door is a teacher at the local school.', 'The man who lives next door is a doctor at the local hospital.', 'The woman who lives next door is a doctor at the local hospital.', 'The woman who lives next door is a nurse at the local hospital.'],
        correct: 2,
        type: 'dictation',
      },
      {
        id: 'en-B1-07',
        audioText: 'The research shows that people who exercise regularly tend to sleep better and feel less stressed. Even thirty minutes of walking a day can make a significant difference.',
        question: 'According to the research, how much walking can help?',
        options: ['Ten minutes', 'Twenty minutes', 'Thirty minutes', 'Sixty minutes'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-B1-08',
        audioText: 'She told me that she had been studying French for three years before she moved to Paris.',
        question: 'How long had she studied French?',
        options: ['One year', 'Two years', 'Three years', 'Four years'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-B1-09',
        audioText: 'I wish I had more time to read books.',
        question: 'What did you hear?',
        options: ['I wish I had more time to read books.', 'I wish I had more money to buy books.', 'I hope I have more time to read books.', 'I wish I had more time to watch movies.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-B1-10',
        audioText: 'The museum is open every day except Monday. Admission is free for students with a valid ID.',
        question: 'When is the museum closed?',
        options: ['Sunday', 'Monday', 'Saturday', 'It\'s always open'],
        correct: 1,
        type: 'comprehension',
      },
    ],
  },
  {
    level: 'B2',
    questions: [
      {
        id: 'en-B2-01',
        audioText: 'While many people assume that artificial intelligence will eliminate jobs, experts suggest it will actually transform the nature of work rather than reduce the overall number of positions available.',
        question: 'What do experts suggest about AI and jobs?',
        options: ['AI will eliminate all jobs', 'AI will create fewer jobs', 'AI will transform work rather than reduce jobs', 'AI has no effect on employment'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-B2-02',
        audioText: 'Had I known about the delay, I would have booked an earlier flight.',
        question: 'What did you hear?',
        options: ['Had I known about the delay, I would have booked an earlier flight.', 'If I knew about the delay, I would book an earlier flight.', 'Had I known about the cancellation, I would have booked an earlier flight.', 'Had I known about the delay, I would have taken the train.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-B2-03',
        audioText: 'The report highlights a growing trend towards remote work, noting that productivity has increased by fifteen percent in companies that offer flexible arrangements. However, some managers remain skeptical about long-term sustainability.',
        question: 'How much has productivity increased according to the report?',
        options: ['Five percent', 'Ten percent', 'Fifteen percent', 'Twenty percent'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-B2-04',
        audioText: 'Not only did she complete the project on time, but she also won an award for it.',
        question: 'What did you hear?',
        options: ['Not only did she complete the project on time, but she also won an award for it.', 'She completed the project on time and won an award.', 'Not only did she finish the report on time, but she also won an award for it.', 'Not only did she complete the project on time, but she also got a promotion.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-B2-05',
        audioText: 'The concept of cultural intelligence suggests that understanding and adapting to different cultural norms is as important as traditional cognitive intelligence in today\'s globalized workplace.',
        question: 'What does cultural intelligence involve?',
        options: ['Speaking multiple languages', 'Understanding and adapting to cultural norms', 'Having a high IQ', 'Traveling frequently'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-B2-06',
        audioText: 'Despite the initial setbacks, the team managed to deliver exceptional results that exceeded everyone\'s expectations.',
        question: 'What did you hear?',
        options: ['Despite the initial setbacks, the team managed to deliver exceptional results that exceeded everyone\'s expectations.', 'Because of the initial setbacks, the team failed to deliver results.', 'Despite the initial success, the team managed to deliver exceptional results.', 'Despite the initial setbacks, the team barely met expectations.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-B2-07',
        audioText: 'The documentary explores how urban farming initiatives are transforming abandoned lots in Detroit into productive community gardens. Residents report not only having access to fresh produce, but also experiencing a stronger sense of community.',
        question: 'What are the TWO benefits mentioned?',
        options: ['Lower prices and better health', 'Fresh produce and community bonds', 'More jobs and fresh produce', 'Better health and exercise'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-B2-08',
        audioText: 'The novelist whose latest book became an international bestseller says she draws inspiration from everyday conversations she overhears in cafes.',
        question: 'Where does the novelist get inspiration?',
        options: ['From traveling', 'From reading other novels', 'From conversations in cafes', 'From her dreams'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-B2-09',
        audioText: 'Having read the instructions carefully, he assembled the furniture without any problems.',
        question: 'What did you hear?',
        options: ['Having read the instructions carefully, he assembled the furniture without any problems.', 'After reading the manual carefully, he assembled the furniture without any problems.', 'Having read the instructions quickly, he assembled the furniture without any problems.', 'Having read the instructions carefully, he assembled the computer without any problems.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-B2-10',
        audioText: 'If she had accepted that job offer five years ago, she would be living in Tokyo now. Sometimes she wonders whether she made the right decision.',
        question: 'What is the speaker expressing?',
        options: ['Certainty about her choice', 'Regret and wondering about what could have been', 'Happiness about staying', 'Plans to move to Tokyo'],
        correct: 1,
        type: 'comprehension',
      },
    ],
  },
  {
    level: 'C1',
    questions: [
      {
        id: 'en-C1-01',
        audioText: 'The notion that multitasking enhances productivity is largely a myth. Neuroscience research has consistently demonstrated that what we perceive as multitasking is actually rapid task-switching, which imposes a cognitive cost and ultimately reduces efficiency.',
        question: 'What does the research say about multitasking?',
        options: ['It significantly improves productivity', 'It is actually rapid task-switching that reduces efficiency', 'It works well for simple tasks', 'It depends on the individual'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-C1-02',
        audioText: 'Scarcely had the announcement been made when the crowd erupted in protest.',
        question: 'What did you hear?',
        options: ['Scarcely had the announcement been made when the crowd erupted in protest.', 'No sooner had the announcement been made than the crowd erupted in protest.', 'Scarcely had the decision been made when the crowd erupted in protest.', 'Scarcely had the announcement been made when the crowd erupted in applause.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-C1-03',
        audioText: 'The philosopher argued that true freedom does not consist in the absence of constraints, but rather in the capacity to act in accordance with one\'s deepest values, even when external pressures suggest otherwise.',
        question: 'What is the philosopher\'s definition of true freedom?',
        options: ['Having no rules or constraints', 'Being wealthy enough to do anything', 'Acting according to one\'s values despite external pressure', 'Following societal expectations'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-C1-04',
        audioText: 'It is imperative that all participants be present at the preliminary hearing scheduled for next Thursday.',
        question: 'What did you hear?',
        options: ['It is imperative that all participants be present at the preliminary hearing scheduled for next Thursday.', 'It is important that all participants are present at the hearing next Thursday.', 'It is imperative that all participants be present at the final hearing scheduled for next Thursday.', 'It is imperative that all members be present at the preliminary hearing scheduled for next Thursday.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-C1-05',
        audioText: 'The paper contends that the correlation between economic growth and environmental degradation is not inevitable. Citing evidence from several Nordic countries, the author demonstrates that robust economic performance can coexist with ambitious sustainability targets.',
        question: 'What does the paper argue?',
        options: ['Economic growth always harms the environment', 'Nordic countries have weak economies', 'Economic growth and environmental protection can coexist', 'Sustainability targets slow economic growth'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-C1-06',
        audioText: 'The suspect is believed to have left the country last week.',
        question: 'What did you hear?',
        options: ['The suspect is believed to have left the country last week.', 'The suspect is believed to leave the country next week.', 'The suspect is known to have left the country last week.', 'The suspect is believed to have left the city last week.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-C1-07',
        audioText: 'Notwithstanding the apparent simplicity of the proposal, several committee members raised concerns about its feasibility, citing insufficient budgetary allocations and a lack of qualified personnel to oversee implementation.',
        question: 'Why were committee members concerned?',
        options: ['The proposal was too complicated', 'Insufficient budget and lack of qualified personnel', 'They disagreed with the goals', 'The timeline was too long'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'en-C1-08',
        audioText: 'The sociolinguist pointed out that language shapes thought in subtle but profound ways. For instance, speakers of languages that use absolute directions instead of relative ones tend to have a superior sense of spatial orientation.',
        question: 'What example does the sociolinguist give?',
        options: ['Bilingual people think faster', 'Some languages have more words for colors', 'Speakers using absolute directions have better spatial orientation', 'Children learn language faster than adults'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'en-C1-09',
        audioText: 'She could have warned us about the changes, but she chose not to.',
        question: 'What did you hear?',
        options: ['She could have warned us about the changes, but she chose not to.', 'She should have warned us about the changes, but she chose not to.', 'She could have told us about the changes, but she chose not to.', 'She could have warned them about the changes, but she chose not to.'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'en-C1-10',
        audioText: 'What distinguishes exceptional leaders from merely competent ones is not their technical expertise, but their ability to foster psychological safety within their teams, enabling open communication and constructive dissent.',
        question: 'According to the speaker, what makes a leader exceptional?',
        options: ['Superior technical skills', 'Many years of experience', 'The ability to create psychological safety for open communication', 'Being strict and decisive'],
        correct: 2,
        type: 'comprehension',
      },
    ],
  },
];

// ── Japanese (JLPT N5–N1) ── 10 questions per level, 5 randomly selected
export const japaneseListeningPool: ListeningLevelBlock[] = [
  {
    level: 'N5',
    questions: [
      {
        id: 'ja-N5-01',
        audioText: 'わたしの なまえは たなかです。にほんじんです。',
        question: 'この人は どこの人ですか？',
        options: ['アメリカ人', '日本人', 'かんこく人', 'ちゅうごく人'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N5-02',
        audioText: 'つくえの うえに ほんが あります。',
        question: 'なにを ききましたか？',
        options: ['つくえの うえに ほんが あります。', 'つくえの したに ほんが あります。', 'つくえの うえに かばんが あります。', 'いすの うえに ほんが あります。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N5-03',
        audioText: 'きょうは にちようびです。あした がっこうに いきます。',
        question: 'きょうは なんようびですか？',
        options: ['げつようび', 'どようび', 'にちようび', 'きんようび'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N5-04',
        audioText: 'わたしは まいあさ コーヒーを のみます。',
        question: 'なにを ききましたか？',
        options: ['わたしは まいあさ コーヒーを のみます。', 'わたしは まいばん コーヒーを のみます。', 'わたしは まいあさ おちゃを のみます。', 'かれは まいあさ コーヒーを のみます。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N5-05',
        audioText: 'この りんごは ひとつ ひゃくえんです。みっつ ください。',
        question: 'りんごを いくつ かいますか？',
        options: ['ひとつ', 'ふたつ', 'みっつ', 'よっつ'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N5-06',
        audioText: 'えきは ここから ちかいです。',
        question: 'なにを ききましたか？',
        options: ['えきは ここから ちかいです。', 'えきは ここから とおいです。', 'がっこうは ここから ちかいです。', 'えきは そこから ちかいです。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N5-07',
        audioText: 'わたしの いぬは しろくて ちいさいです。',
        question: 'いぬは どんな いぬですか？',
        options: ['おおきくて くろい', 'しろくて おおきい', 'しろくて ちいさい', 'くろくて ちいさい'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N5-08',
        audioText: 'かぞくは よにんです。ちちと ははと あにと わたしです。',
        question: 'かぞくは なんにんですか？',
        options: ['さんにん', 'よにん', 'ごにん', 'ろくにん'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N5-09',
        audioText: 'すみません、トイレは どこですか。',
        question: 'なにを ききましたか？',
        options: ['すみません、えきは どこですか。', 'すみません、トイレは どこですか。', 'すみません、でぐちは どこですか。', 'すみません、トイレは ありますか。'],
        correct: 1,
        type: 'dictation',
      },
      {
        id: 'ja-N5-10',
        audioText: 'あしたは あめです。かさを もってきてください。',
        question: 'あしたの てんきは なんですか？',
        options: ['はれ', 'くもり', 'あめ', 'ゆき'],
        correct: 2,
        type: 'comprehension',
      },
    ],
  },
  {
    level: 'N4',
    questions: [
      {
        id: 'ja-N4-01',
        audioText: 'つぎは しぶやえきです。おでぐちは みぎがわです。おわすれものの ないよう ごちゅういください。',
        question: 'おでぐちは どちらがわですか？',
        options: ['ひだりがわ', 'みぎがわ', 'まえ', 'うしろ'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N4-02',
        audioText: 'しゅくだいを してから、あそびに いきます。',
        question: 'なにを ききましたか？',
        options: ['しゅくだいを してから、あそびに いきます。', 'しゅくだいを しないで、あそびに いきます。', 'しゅくだいを してから、かいものに いきます。', 'べんきょうを してから、あそびに いきます。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N4-03',
        audioText: 'すみません、このシャツの えすサイズは ありますか。すみません、えすサイズは うりきれです。えむサイズなら あります。',
        question: 'えすサイズは ありますか？',
        options: ['はい、あります', 'いいえ、うりきれです', 'あしたきます', 'わかりません'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N4-04',
        audioText: 'あした てんきが よかったら、ピクニックに いきましょう。',
        question: 'なにを ききましたか？',
        options: ['あした てんきが よかったら、ピクニックに いきましょう。', 'あした てんきが わるかったら、ピクニックに いきましょう。', 'あした てんきが よかったら、うみに いきましょう。', 'きょう てんきが よかったら、ピクニックに いきましょう。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N4-05',
        audioText: 'わたしは きょねん にほんに きました。まだ いちねんですが、にほんごが すこし はなせるように なりました。',
        question: 'この人は にほんに いつ きましたか？',
        options: ['さくねん', 'にねんまえ', 'せんげつ', 'さんねんまえ'],
        correct: 0,
        type: 'comprehension',
      },
      {
        id: 'ja-N4-06',
        audioText: 'せんせいに ほめられて うれしかったです。',
        question: 'なにを ききましたか？',
        options: ['せんせいに おこられて かなしかったです。', 'せんせいに ほめられて うれしかったです。', 'せんせいに ほめられて はずかしかったです。', 'ともだちに ほめられて うれしかったです。'],
        correct: 1,
        type: 'dictation',
      },
      {
        id: 'ja-N4-07',
        audioText: 'この レストランは やすくて おいしいので、いつも こんでいます。よやくしたほうが いいですよ。',
        question: 'レストランについて ただしいのは どれですか？',
        options: ['たかいけど おいしい', 'やすくて おいしいから こんでいる', 'すいている', 'まずい'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N4-08',
        audioText: 'まどが あいています。さむいから しめてください。',
        question: 'なにを たのんでいますか？',
        options: ['まどを あけること', 'まどを しめること', 'エアコンを つけること', 'でんきを けすこと'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N4-09',
        audioText: 'きのう はじめて すしを つくりました。',
        question: 'なにを ききましたか？',
        options: ['きのう はじめて すしを つくりました。', 'きのう はじめて すしを たべました。', 'きょう はじめて すしを つくりました。', 'きのう はじめて ケーキを つくりました。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N4-10',
        audioText: 'はは は まいにち やさいを たべるように しています。けんこうの ためだ そうです。',
        question: 'おかあさんは なぜ やさいを たべますか？',
        options: ['やすいから', 'おいしいから', 'けんこうのため', 'ダイエットのため'],
        correct: 2,
        type: 'comprehension',
      },
    ],
  },
  {
    level: 'N3',
    questions: [
      {
        id: 'ja-N3-01',
        audioText: 'てんきよほうによると、こんしゅうまつは ぜんこくてきに はれるそうです。ただし、きたのちほうでは きおんが ひくくなるようです。',
        question: 'こんしゅうまつの てんきは どうですか？',
        options: ['ぜんこくで あめ', 'ぜんこくで はれ、ただし きたは さむい', 'きたは はれ、みなみは あめ', 'どこも くもり'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N3-02',
        audioText: 'せつめいしょを よんだのに、つかいかたが わからない。',
        question: 'なにを ききましたか？',
        options: ['せつめいしょを よんだのに、つかいかたが わからない。', 'せつめいしょを よまなかったので、つかいかたが わからない。', 'せつめいしょを よんだから、つかいかたが わかった。', 'せつめいしょを よんだのに、こわれてしまった。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N3-03',
        audioText: 'わたしは にほんに きてから、さいしょは にほんごが ぜんぜん わかりませんでした。でも、まいにち テレビを みて、ともだちと はなすうちに、すこしずつ わかるように なりました。',
        question: 'この人は どうやって にほんごが うまくなりましたか？',
        options: ['にほんごがっこうに かよった', 'テレビと ともだちとの かいわで', 'ほんを たくさん よんだ', 'オンラインで べんきょうした'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N3-04',
        audioText: 'でんしゃが おくれた せいで、かいぎに まにあわなかった。',
        question: 'なにを ききましたか？',
        options: ['でんしゃが おくれた せいで、かいぎに まにあわなかった。', 'でんしゃが おくれた おかげで、かいぎに まにあった。', 'バスが おくれた せいで、かいぎに まにあわなかった。', 'でんしゃが おくれた せいで、しごとに まにあわなかった。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N3-05',
        audioText: 'この まちは むかし しずかな ところでした。でも、えきが できてから、びるや みせが ふえて、とても にぎやかに なりました。べんりに なったはんめん、みどりが すくなくなったのは ざんねんです。',
        question: 'この人は まちの へんかについて どう おもっていますか？',
        options: ['よいことばかり', 'わるいことばかり', 'べんりだが みどりがへったのは ざんねん', 'なにもかわっていない'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N3-06',
        audioText: 'にほんごが すこし はなせるように なりました。',
        question: 'なにを ききましたか？',
        options: ['にほんごが すこし はなせるように なりました。', 'にほんごが じょうずに はなせるように なりました。', 'にほんごが すこし よめるように なりました。', 'えいごが すこし はなせるように なりました。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N3-07',
        audioText: 'さいきんは ネットで かいものを する人が ふえています。みせに いかなくても、いえから ちゅうもんできるので べんりです。しかし、じっさいに しなものを みられないという デメリットも あります。',
        question: 'ネットかいものの デメリットは なんですか？',
        options: ['たかい', 'じかんが かかる', 'しなものを じっさいに みられない', 'しゅるいが すくない'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N3-08',
        audioText: 'いそがしいからといって、けんこうを むしするべきではない。',
        question: 'なにを ききましたか？',
        options: ['いそがしいからといって、けんこうを むしするべきではない。', 'いそがしいから、けんこうを むししてもいい。', 'いそがしいからといって、しごとを やめるべきではない。', 'いそがしくないから、けんこうに きをつけよう。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N3-09',
        audioText: 'わたしは ふじさんに のぼったことが あります。てっぺんからの けしきは ほんとうに すばらしかったです。',
        question: 'てっぺんからの けしきは どうでしたか？',
        options: ['こわかった', 'つまらなかった', 'すばらしかった', 'みえなかった'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N3-10',
        audioText: 'きゅうに あめに ふられて、かさが なくて こまりました。',
        question: 'なぜ こまりましたか？',
        options: ['でんしゃが こなかった', 'みちに まよった', 'あめが ふって かさが なかった', 'おかねが なかった'],
        correct: 2,
        type: 'comprehension',
      },
    ],
  },
  {
    level: 'N2',
    questions: [
      {
        id: 'ja-N2-01',
        audioText: 'きんねんの けんきゅうにより、すいみんぶそくが のうの きのうに あたえる えいきょうは、これまで かんがえられていた いじょうに ふかこくである ことが あきらかになりました。とくに、きおくの ていちゃくや そうぞうてきな しこうに おおきな えいきょうが あるとの ことです。',
        question: 'すいみんぶそくは とくに なにに えいきょうが ありますか？',
        options: ['うんどうのうりょく', 'しりょく', 'きおくと そうぞうてきしこう', 'たいじゅう'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N2-02',
        audioText: 'にほんごを さんねん べんきょうした ものの、まだ じょうずに はなせない。',
        question: 'なにを ききましたか？',
        options: ['にほんごを さんねん べんきょうした ものの、まだ じょうずに はなせない。', 'にほんごを さんねん べんきょうしたので、じょうずに はなせる。', 'にほんごを ごねん べんきょうした ものの、まだ じょうずに はなせない。', 'にほんごを さんねん べんきょうした ものの、まだ じょうずに かけない。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N2-03',
        audioText: 'かいしゃの ほうしんとして、らいねんから リモートワークを ほんかくてきに どうにゅうすることが けっていされました。しゃいんの まんぞくどが たかまるいっぽうで、コミュニケーションの かだいも しんちょうに たいおうする ひつようが あると、ぶちょうは はなしました。',
        question: 'リモートワークの かだいは なんですか？',
        options: ['コストが たかい', 'コミュニケーション', 'せいさんせいが ひくい', 'セキュリティ'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N2-04',
        audioText: 'あしたは たいせつな しけんだから、べんきょうしない わけにはいかない。',
        question: 'なにを ききましたか？',
        options: ['あしたは たいせつな しけんだから、べんきょうしない わけにはいかない。', 'あしたは たいせつな しけんだから、べんきょうしなくてもいい。', 'あしたは たいせつな かいぎだから、べんきょうしない わけにはいかない。', 'あしたは たいせつな しけんだが、べんきょうしたくない。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N2-05',
        audioText: 'にほんの しょくぶんかは たんに あじだけでなく、もりつけや しきかんも じゅうしされます。はるには さくらもち、なつには そうめんなど、きせつに あわせた りょうりを たのしむ ぶんかが あります。',
        question: 'にほんの しょくぶんかで じゅうしされるのは なんですか？',
        options: ['りょうだけ', 'あじだけ', 'あじ、もりつけ、きせつかん', 'かかくと りょう'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N2-06',
        audioText: 'かれは プロの おんがくか だけあって、えんそうが すばらしい。',
        question: 'なにを ききましたか？',
        options: ['かれは プロの おんがくか だけあって、えんそうが すばらしい。', 'かれは プロの おんがくか にしては、えんそうが すばらしい。', 'かれは プロの おんがくか だけあって、うたが すばらしい。', 'かのじょは プロの おんがくか だけあって、えんそうが すばらしい。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N2-07',
        audioText: 'さいきん、わかい せだいを ちゅうしんに、ちほうに いじゅうする ひとが ふえています。とかいの いそがしい せいかつに つかれ、しぜんの なかで ゆっくり くらしたいと かんがえる ひとが おおいようです。',
        question: 'なぜ ちほうに いじゅうする ひとが ふえていますか？',
        options: ['しごとが おおいから', 'とかいの せいかつに つかれたから', 'ちほうが べんりだから', 'ともだちが いるから'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N2-08',
        audioText: 'あたたかい うちに、たべてください。',
        question: 'どういう いみですか？',
        options: ['あたたかい へやで たべてください', 'さめないうちに たべてください', 'あとで たべてください', 'つめたくして たべてください'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N2-09',
        audioText: 'この もんだいに かんして、もうすこし しらべる ひつようが ある。',
        question: 'なにを ききましたか？',
        options: ['この もんだいに かんして、もうすこし しらべる ひつようが ある。', 'この もんだいに ついて、しらべる ひつようは ない。', 'この もんだいに かんして、もう しらべおわった。', 'この じけんに かんして、もうすこし しらべる ひつようが ある。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N2-10',
        audioText: 'とかいは べんりな いっぽうで、やちんが たかい。しかし、さいきんでは ちほうでも テレワークが かのうになり、とかいに すむ ひつようせいを さいけんとうする ひとが ふえている。',
        question: 'さいきんの けいこうは なんですか？',
        options: ['とかいに ひっこす ひとが ふえている', 'ちほうに ひっこす ひとが ふえている', 'テレワークが へっている', 'やちんが さがっている'],
        correct: 1,
        type: 'comprehension',
      },
    ],
  },
  {
    level: 'N1',
    questions: [
      {
        id: 'ja-N1-01',
        audioText: 'げんだいしゃかいにおいて、じょうほうリテラシーの じゅうようせいは いっそう たかまっている。インターネットじょうの ぼうだいな じょうほうの なかから、しんぴょうせいの たかい じょうほうを みきわめる のうりょくが、いまや ふかけつと いえるだろう。',
        question: 'じょうほうリテラシーとして もっとも じゅうような のうりょくは なんですか？',
        options: ['じょうほうを はやく あつめる のうりょく', 'しんぴょうせいの たかい じょうほうを みきわめる のうりょく', 'たくさんの じょうほうを きおくする のうりょく', 'じょうほうを はっしんする のうりょく'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N1-02',
        audioText: 'この プロジェクトの せいこうは、チームぜんいんの きょうりょくの たまものだ。',
        question: 'なにを ききましたか？',
        options: ['この プロジェクトの せいこうは、チームぜんいんの きょうりょくの たまものだ。', 'この プロジェクトの しっぱいは、チームぜんいんの せきにんだ。', 'この プロジェクトの せいこうは、リーダーの のうりょくの たまものだ。', 'この プロジェクトの せいこうは、チームぜんいんの どりょくの けっかだ。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N1-03',
        audioText: 'げんごがくの けんきゅうでは、ぼごが しこうパターンに えいきょうを あたえるかについて ながねん ぎろんが つづいている。さいきんの しんけいかがくてき けんきゅうにより、げんごの こうぞうが にんちプロセスに じっさいに えいきょうを およぼす というしょうこが しだいに つみかさなっている。',
        question: 'さいきんの けんきゅうで わかってきた ことは なんですか？',
        options: ['ぼごは しこうに えいきょうしない', 'げんごの こうぞうは にんちプロセスに えいきょうする', 'すべての げんごは おなじ こうぞうをもつ', 'しんけいかがくは やくにたたない'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N1-04',
        audioText: 'ほんじつをもって、おうぼを しめきらせていただきます。',
        question: 'なにを ききましたか？',
        options: ['ほんじつをもって、おうぼを しめきらせていただきます。', 'ほんじつをもって、えいぎょうを しゅうりょうさせていただきます。', 'らいしゅうをもって、おうぼを しめきらせていただきます。', 'ほんじつをもって、じゅぎょうを しめきらせていただきます。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N1-05',
        audioText: 'かんきょうもんだいに たいする きぎょうの とりくみは、たんなる しゃかいてき せきにんに とどまらず、ちょうきてきな きょうそうゆういの かくとくにも つながるという してんが、けいえいがくの ぶんやで ちゅうもくされている。',
        question: 'きぎょうの かんきょうの とりくみは なにに つながりますか？',
        options: ['たんきてきな りえき', 'しゃかいてき ひはん', 'ちょうきてきな きょうそうゆうい', 'じゅうぎょういんの まんぞく'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N1-06',
        audioText: 'しゅういの しんぱいを よそに、かれは ひとりで やまに むかった。',
        question: 'なにを ききましたか？',
        options: ['しゅういの しんぱいを よそに、かれは ひとりで やまに むかった。', 'しゅういの しんぱいもあり、かれは やまに いかなかった。', 'しゅういの しんぱいを よそに、かれは ひとりで うみに むかった。', 'しゅういの はんたいを よそに、かれは ひとりで やまに むかった。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N1-07',
        audioText: 'にほんの でんとうげいのうは、たんなる ごらくの えんげいに とどまらず、れきしてき・しゃかいてき はいけいを はんえいした そうごうげいじゅつである。のうがくを れいに とると、うたい、まい、がくきえんそうが ゆうきてきに けつごうし、ひとつの せかいかんを きずきあげている。',
        question: 'にほんの でんとうげいのうの とくちょうは なんですか？',
        options: ['たんじゅんな ごらく', 'れきしてき はいけいを はんえいした そうごうげいじゅつ', 'がいこくから つたわった げいじゅつ', 'きんだいに つくられた げいじゅつ'],
        correct: 1,
        type: 'comprehension',
      },
      {
        id: 'ja-N1-08',
        audioText: 'その えいがを みたら、なかずには いられない。',
        question: 'どういう いみですか？',
        options: ['なきたくないけど なく', 'ぜったいに なかない', 'かならず なく', 'なくかもしれない'],
        correct: 2,
        type: 'comprehension',
      },
      {
        id: 'ja-N1-09',
        audioText: 'りゆうの いかんによらず、ぼうりょくは ゆるされない。',
        question: 'なにを ききましたか？',
        options: ['りゆうの いかんによらず、ぼうりょくは ゆるされない。', 'りゆうによっては、ぼうりょくは ゆるされる。', 'りゆうの いかんによらず、さべつは ゆるされない。', 'りゆうの いかんでは、ぼうりょくは ゆるされる。'],
        correct: 0,
        type: 'dictation',
      },
      {
        id: 'ja-N1-10',
        audioText: 'AIぎじゅつの しんてんは めざましいが、それが にんげんの そうぞうせいを おぎなう ものなのか、それとも だいたいする ものなのかについて、せんもんかの あいだでも いけんが わかれている。じゅうような ことは、ぎじゅつの しんかに あわせて、しゃかいぜんたいで りんりてきな わくぐみを せいびする ことではないだろうか。',
        question: 'はなしての もっとも いいたい ことは なんですか？',
        options: ['AIは にんげんより すぐれている', 'AIは きけんだから きんしすべき', 'AIの しんかに あわせて りんりてきな わくぐみが ひつよう', 'せんもんかは AIに さんせいしている'],
        correct: 2,
        type: 'comprehension',
      },
    ],
  },
];
